name = "pet-store"
main = "./index.js"
compatibility_date = "2024-07-16"

[dev]
port = 4444


[env.dev]
  vars = { FIREBASE_DB = "https://petstore-eb41f-default-rtdb.europe-west1.firebasedatabase.app" }

[env.prod]
  vars = { FIREBASE_DB = "https://petstore-eb41f-default-rtdb.europe-west1.firebasedatabase.app" }

# Default vars for general environment if no specific environment is selected
[vars]
  FIREBASE_DB = "https://petstore-eb41f-default-rtdb.europe-west1.firebasedatabase.app"
  